### ISSUE TITLE
Tests failing on ci

### ISSUE THREAD

**Issue by usmandap** [sylvaindumont/docker-node-karma-protractor-chrome#8]
Any idea I am getting error `UnexpectedAlertOpen` previously these tests were passing also they are still passing for me locally. Is it due to new update of this package?
![screen shot 2560-11-14 at 3 26 40 pm](https://user-images.githubusercontent.com/15185299/32775204-95421696-c950-11e7-8b6f-3eae3a43df77.png)

**Comment by sylvaindumont** [comment]
This image hasn't changed since spetember, if you got these errors recently it's likely not due to an update of this package.
https://hub.docker.com/r/weboaks/node-karma-protractor-chrome/ is rebuilt each time node base image is updated, so it may be related to an update in the base image.
In the alpine version of the image, chromedriver is from the alpine repos, so it can be a version mismatch.

You can work around this problem by addyng `browser.switchTo().alert().accept();` to your protractor tests.

**Comment by usmandap** [comment]
@sylvaindumont Alright, but why on ducker hub it is showing that it was updated 5 days ago that's why I asked.
https://hub.docker.com/r/weboaks/node-karma-protractor-chrome/builds/
Thanks

**Comment by sylvaindumont** [comment]
Docker hub display the date of the latest build, and the image is automatically rebuild each time the base image is updated. Node have been updated 5 days ago so docker hub have rebuilt this image 5 days ago.

**Comment by usmandap** [comment]
@sylvaindumont Got it thanks for your help, appreciated.
